### ISSUE TITLE
Losse opdrachten verwerken in de hoofdopdracht

### ISSUE THREAD

**Issue by MicheleNL** [beemstb002/CSSToTheRescue#1]
Ik zag je notitie over de losse opdrachten en de eindopdracht. Verwerk de losse opdrachten toch maar even in de eindopdracht. Dit is erg lastig  te beoordelen zo.

**Comment by beemstb002** [comment]
Ik heb alle code opnieuw geschreven. Alle feedback is erin verwerkt en de modal is nu te openen via een link in de navigatie. http://www.beemsterwebdesign.nl/csstotherescue/
